import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { Poppins } from "next/font/google";
import "./globals.css";
import Header from "@/components/ui/header/Header";
import Sidebar from "@/components/ui/Sidebar";
import { Playfair_Display, Montserrat } from "next/font/google";

const playfair = Playfair_Display({
  subsets: ["latin"],
  weight: ["600", "700"], // bold for headings
  variable: "--font-heading",
});

const montserrat = Montserrat({
  subsets: ["latin"],
  weight: ["400", "500"], // normal for body
  variable: "--font-body",
});

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});
const poppins = Poppins({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en"     className={`${playfair.variable} ${poppins.className} ${montserrat.variable}`}>
      <body
      // className={`${geistSans.variable} ${geistMono.variable} antialiased flex`}
      >
        {/* <Sidebar /> */}

        <div className=" bg-gray-50 overflow-hidden flex w-full h-screen flex-col   dark:bg-gray-950">
          {/* <Header /> */}
          {/* <div>ok</div> */}
          <main className="overflow-hidden ">{children}</main>
        </div>
      </body>
    </html>
    // <html lang="en">
    //   <body
    //     className={`${geistSans.variable} ${geistMono.variable} antialiased flex h-screen m-0`}
    //   >
    //     {/* Sidebar could go here */}

    //     <div className="flex-1 flex flex-col bg-pink-500 dark:bg-gray-950">
    //       {/* Header could go here */}

    //       <main className="flex-1 overflow-y-auto p-6">{children}</main>
    //     </div>
    //   </body>
    // </html>
  );
}
